// The business-plan library shown after signup. Each plan routes to the right
// monetization CTA: shippable products -> Shopify, local/service businesses -> GoHighLevel.
export type PlanType = "shopify" | "ghl";

export interface Plan {
  slug: string;
  title: string;
  type: PlanType;
  blurb: string;
  /** Alibaba search term for the cheapest key input. */
  supplier: string;
}

export const PLANS: Plan[] = [
  { slug: "loaded-fruit-cups", title: "Loaded Fruit Cups", type: "ghl", blurb: "Fresh layered fruit-cocktail cups — a high-margin local dessert kiosk.", supplier: "clear PET cups with lids" },
  { slug: "holographic-chocolate", title: "Holographic Chocolate", type: "shopify", blurb: "Edible rainbow chocolate bars — a premium giftable product you ship.", supplier: "diffraction grating film sheets" },
  { slug: "espresso-popsicles", title: "Espresso Popsicles", type: "ghl", blurb: "Frozen latte pops — the cafe summer upsell nobody's doing.", supplier: "popsicle sleeve bags" },
  { slug: "tote-wall-storage", title: "Tote Wall Storage", type: "ghl", blurb: "Custom garage tote-wall installs — a local service + plans/kit.", supplier: "27 gallon heavy duty storage totes" },
  { slug: "cheesecake-pops", title: "Cheesecake Pops", type: "ghl", blurb: "Decorated cheesecake cakesicles — start with supermarket cheesecake.", supplier: "cakesicle silicone molds" },
  { slug: "dessert-cups", title: "Dessert Cups", type: "ghl", blurb: "Layered tiramisu/matcha dessert cups — a grab-and-go flavor wall.", supplier: "clear dessert cups with dome lids" },
  { slug: "nail-printing", title: "Nail Printing", type: "ghl", blurb: "Instant digital nail-art printing — salon/kiosk/event service.", supplier: "digital nail printer machine" },
  { slug: "souvenir-popsicles", title: "Souvenir Popsicles", type: "ghl", blurb: "3D sculpted landmark gelato pops — sell where tourists already are.", supplier: "3D silicone popsicle molds" },
  { slug: "the-tv-that-disappears", title: "The TV That Disappears", type: "shopify", blurb: "Mirror TVs that vanish into the wall — a premium product you sell + ship.", supplier: "mirror tv glass two way" },
  { slug: "snap-on-tiles", title: "Snap-On Tiles", type: "shopify", blurb: "Interlocking garage floor tiles — a shippable home-improvement product.", supplier: "garage floor tiles interlocking" },
  { slug: "foam-parties", title: "Foam Parties", type: "ghl", blurb: "Foam-cannon party rentals — fast-ROI local events service.", supplier: "foam machine cannon party" },
  { slug: "light-bulb-drinks", title: "Light Bulb Drinks", type: "ghl", blurb: "Novelty light-bulb-bottle shakes — the most photogenic drink in town.", supplier: "light bulb shaped drink bottles" },
  { slug: "virtual-graffiti-wall", title: "Virtual Graffiti Wall", type: "ghl", blurb: "Mess-free digital graffiti for events — a photo-booth on steroids at $350-550/hr.", supplier: "LED video wall panels" },
  { slug: "stamp-card-loyalty-engine", title: "The Stamp Card Loyalty Engine", type: "ghl", blurb: "A done-for-you stamp-card loyalty program that turns one-time buyers into repeat regulars for any local shop.", supplier: "custom printed loyalty stamp cards" },
  { slug: "court-fx-led-sport-courts", title: "Court FX — Programmable LED Sport Courts", type: "ghl", blurb: "Install and rent color-changing programmable LED courts that turn one slab into a hundred different arenas.", supplier: "interactive LED sport court floor tiles" },
  { slug: "printhaus-3d-construction", title: "PrintHaus 3D Construction", type: "ghl", blurb: "Print houses and backyard ADUs layer by layer, cutting build costs up to 45 percent.", supplier: "3d concrete printer construction gantry" },
  { slug: "minimelt-mini-ice-creams-on-sticks", title: "MiniMelt — Mini Ice Creams On Sticks", type: "ghl", blurb: "Sell photogenic racks of mini ice cream pops so customers taste several flavors and film it.", supplier: "mini popsicle silicone mold commercial" },
  { slug: "unscannable-qr-stunt", title: "The Unscannable QR Stunt", type: "ghl", blurb: "A guerrilla marketing stunt where a moving QR code crowd-chases its way to thousands of free brand impressions.", supplier: "wearable sandwich board sign with QR" },
  { slug: "chipkey-implantable-rfid-service", title: "ChipKey — Implantable RFID Payment & Access Service", type: "ghl", blurb: "A mobile service that implants NFC chips so clients unlock doors, share cards, and tap to pay with a wave.", supplier: "NFC RFID implant bioglass chip injector" },
  { slug: "herobox-pizza-packaging", title: "HeroBox Pizza Packaging", type: "shopify", blurb: "Superhero-printed pizza boxes turn customers into walking billboards and pizzerias into your wholesale buyers.", supplier: "custom printed pizza box corrugated" },
  { slug: "frybox-automated", title: "FryBox Automated", type: "ghl", blurb: "Automated fry vending machine serves hot fresh fries in 35 seconds, no staff needed.", supplier: "automatic french fries vending machine" },
  { slug: "mistguard-touchless-sunscreen-booths", title: "MistGuard — Touchless Sunscreen Booths", type: "ghl", blurb: "Pay-per-spray sunscreen booths at beaches and resorts that earn around twelve thousand a month each.", supplier: "automatic spray tanning sunscreen booth machine" },
  { slug: "floating-lemon-challenge", title: "The Floating Lemon Challenge", type: "ghl", blurb: "A near-impossible coin-balancing game that turns a cheap prop into entry fees and viral foot traffic.", supplier: "tall glass cylinder vase" },
  { slug: "wabi-beds", title: "Wabi Beds", type: "shopify", blurb: "Handcrafted wabi-sabi beds from raw wood and stone, each one unique and sold at premium prices.", supplier: "live edge wood slab bed frame" },
  { slug: "brewbot-kiosk", title: "BrewBot Kiosk", type: "ghl", blurb: "Self-serve coffee kiosk grinds, brews, and serves fresh coffee in 30 seconds, 24/7.", supplier: "automatic coffee vending machine fresh bean" },
  { slug: "balloon-surprise-towers", title: "Balloon Surprise Towers", type: "ghl", blurb: "Tall balloon towers stuffed with plushies and surprise gifts, sold for birthdays, weddings and showers.", supplier: "stuffed animals bulk wholesale" },
  { slug: "popshop-displays", title: "PopShop Displays", type: "shopify", blurb: "Import flat-folding retail displays that pop open in 3 seconds and resell to pop-up vendors at huge margins.", supplier: "collapsible pop-up retail display stand" },
  { slug: "ice-vending-machine-business", title: "The Ice Vending Machine Business", type: "ghl", blurb: "A self-service ice vending machine that sells frozen water 24/7 with no staff and high seasonal margins.", supplier: "commercial ice vending machine" },
  { slug: "popshop-fold-flat-mobile-retail", title: "PopShop — Fold-Flat Mobile Retail", type: "ghl", blurb: "Run a portable store using fold-flat display cabinets that pop open anywhere foot traffic is highest.", supplier: "folding portable retail display showcase cabinet" },
  { slug: "bloom-bubble", title: "Bloom Bubble", type: "ghl", blurb: "Fresh bouquets sealed inside clear balloons sold as premium giftable flowers with same-day local delivery.", supplier: "clear bobo balloon bulk stuffing machine" },
  { slug: "saucelab-vending", title: "SauceLab Vending", type: "ghl", blurb: "Custom-sauce vending machine mixes 2,000+ flavor combos, turning every order into shareable content.", supplier: "custom sauce dispenser vending machine" },
  { slug: "custom-collectible-lighters", title: "Custom Collectible Lighters", type: "shopify", blurb: "Plain bulk lighters re-wrapped with custom art and sold as collectible, giftable accessories at huge margins.", supplier: "refillable lighters bulk" },
  { slug: "cubebrand-giant-selfie-cubes-for-events", title: "CubeBrand — Giant Selfie Cubes For Events", type: "ghl", blurb: "Rent branded selfie cubes to events so guests post photos and spread the logo for free.", supplier: "portable aluminum exhibition booth frame truss" },
  { slug: "sweet-taco-co", title: "Sweet Taco Co.", type: "ghl", blurb: "Sell viral dessert tacos with chocolate-dipped waffle shells from a stall or cart at 80% food margins.", supplier: "waffle taco shell maker machine" },
  { slug: "all-in-one-disposable-tea-cups", title: "All-In-One Disposable Tea Cups", type: "shopify", blurb: "Disposable cups with tea pre-loaded in a bottom filter, sold to convenience-loving households, offices, and hotels.", supplier: "disposable tea cup with built-in filter" },
  { slug: "frostcup-minus-86-latte", title: "Frostcup Coffee — The Minus-86 Latte", type: "ghl", blurb: "A cafe concept serving lattes in frost-crusted cups frozen to minus 86 degrees that customers can't help but film.", supplier: "minus 86 ULT laboratory freezer" },
  { slug: "peardip-tea", title: "PearDip Tea", type: "shopify", blurb: "Pear-shaped novelty teabags that brew normally but spread on social media as built-in marketing.", supplier: "novelty shaped tea bag custom fruit" },
  { slug: "lookbook-ai-studio", title: "Lookbook AI Studio", type: "ghl", blurb: "Turn one flat product photo into a full cinematic ad campaign and lookbook using AI tools.", supplier: "AI product photography service" },
  { slug: "gold-filled-engraved-perfume-bottles", title: "Gold-Filled Engraved Perfume Bottles", type: "shopify", blurb: "Personalized perfume bottles engraved with a name and filled with gold, sold as premium wedding keepsakes.", supplier: "refillable glass perfume bottle" },
  { slug: "tuberoast-flying-beans-cafe", title: "TubeRoast — The Flying-Beans Café", type: "ghl", blurb: "A café that sends beans through overhead glass tubes, turning every order into viral free marketing.", supplier: "clear acrylic pneumatic tube conveyor system" },
  { slug: "bloom-and-drive", title: "Bloom & Drive", type: "shopify", blurb: "Handmake natural dried-flower car air fresheners for pennies and sell them on Etsy for $24-$28 each.", supplier: "car vent essential oil diffuser clip" },
  { slug: "realistic-fruit-candles", title: "Realistic Fruit Candles", type: "shopify", blurb: "Hyper-realistic fruit-shaped candles, like a lightable pomegranate, sold as premium seasonal gifts and home decor.", supplier: "soy candle making wax bulk" },
  { slug: "tidytissue-box-with-built-in-bin", title: "TidyTissue — The Tissue Box With a Built-In Bin", type: "shopify", blurb: "A redesigned tissue box with a hidden trash chamber underneath so used tissues drop straight back inside.", supplier: "tissue box with built-in trash compartment" },
  { slug: "cantee", title: "CanTee", type: "shopify", blurb: "T-shirts sealed in reusable seed-packed cans that customers replant and film, fueling free unboxing reach.", supplier: "custom printed tin can t-shirt packaging" },
  { slug: "window-matcha", title: "Window Matcha", type: "ghl", blurb: "Run a photogenic matcha bar where every drink is served through a tiny window customers film for free marketing.", supplier: "ceremonial matcha powder bulk" },
  { slug: "brickbite-build-your-meal-lego-restaurant", title: "BrickBite — Build-Your-Meal LEGO Restaurant", type: "ghl", blurb: "An experiential restaurant where families order by building meals from branded bricks delivered via conveyor.", supplier: "conveyor belt sushi restaurant delivery system" },
  { slug: "shakestation-vending", title: "ShakeStation Vending", type: "ghl", blurb: "Self-serve protein-shake vending machines in busy gyms earning thousands monthly with no staff or storefront.", supplier: "automatic protein shake vending machine" },
  { slug: "mini-menu-models", title: "Mini Menu Models", type: "ghl", blurb: "Miniature replica dishes mounted on restaurant menus so diners see exactly what they order before buying.", supplier: "fake food model replica" },
  { slug: "self-extinguishing-pocket-ashtray", title: "Self-Extinguishing Pocket Ashtray", type: "shopify", blurb: "Cup-shaped eco ashtrays that self-extinguish with water, sold in bulk to cafes and to smokers online.", supplier: "portable pocket ashtray" },
  { slug: "archpop-rentals", title: "ArchPop Rentals", type: "ghl", blurb: "Rent self-inflating balloon arch setups per event, installing in 15 minutes and charging hundreds each time.", supplier: "automatic balloon arch making machine" },
  { slug: "cologne-vending-machine-business", title: "The Cologne Vending Machine Business", type: "ghl", blurb: "A pay-per-spray cologne vending machine placed in gyms and clubs for near-90% margins and semi-passive income.", supplier: "perfume vending machine" },
  { slug: "linebot-robotic-line-striping-service", title: "LineBot — Robotic Line-Striping Service", type: "ghl", blurb: "A line-striping service run by a painting robot that re-marks parking lots, warehouses, and courts on repeat.", supplier: "autonomous robot line marking machine" },
  { slug: "traceart-murals", title: "TraceArt Murals", type: "ghl", blurb: "Paint custom murals and seasonal window art by tracing an AR projection, charging artist prices without drawing skill.", supplier: "ar vr headset mural projector" },
  { slug: "phantom-studio-ai", title: "Phantom Studio AI", type: "ghl", blurb: "Done-for-you AI agency creating luxury product photos and ad campaigns with no studio or models.", supplier: "AI product photography service" },
  { slug: "pro-rug-cleaning-service", title: "Pro Rug Cleaning Service", type: "ghl", blurb: "Deep-cleaning area rugs at $40 each with satisfying before/after content, a service few towns offer.", supplier: "rug cleaning machine" },
  { slug: "walllumen-modular-led-screen-installs", title: "WallLumen — Modular LED Screen Installs", type: "ghl", blurb: "Install modular LED screens on walls and earn three ways: sell, rent, or run local ads.", supplier: "modular outdoor LED display screen panel P4" },
  { slug: "shatter-coffee", title: "Shatter Coffee", type: "ghl", blurb: "Run a cafe whose frozen-chocolate cups shatter into the coffee, turning every order into filmable free marketing.", supplier: "chocolate cup shell mold" },
  { slug: "butterfly-drone-ring-delivery", title: "Butterfly Drone Ring Delivery", type: "ghl", blurb: "A butterfly-shaped drone delivers wedding rings mid-ceremony, selling couples the most-photographed moment of their day.", supplier: "butterfly drone flying toy" },
  { slug: "doseglow-single-capsule-skincare", title: "DoseGlow — Single-Capsule Skincare", type: "shopify", blurb: "A skincare brand selling perfectly measured single-dose capsules instead of bottles — no waste, travel-ready, subscription-driven.", supplier: "skincare capsule single dose private label" },
  { slug: "totebake-cookies", title: "ToteBake Cookies", type: "ghl", blurb: "Premium giftable cookies packaged in branded mini totes that customers film, multiplying sales through shareable presentation.", supplier: "mini canvas tote bag custom logo" },
  { slug: "skyclean-drone-facade-cleaning", title: "SkyClean Drone Facade Cleaning", type: "ghl", blurb: "Drone-based exterior cleaning for building facades and billboards, replacing dangerous rope and scaffold crews.", supplier: "facade cleaning drone" },
  { slug: "e-bike-conversion-kits", title: "E-Bike Conversion Kits", type: "shopify", blurb: "Bolt-on motor kits that turn any regular bicycle into an e-bike for a third of the price.", supplier: "ebike conversion kit" },
  { slug: "skyfit-rooftop-track-gym", title: "SkyFit — The Rooftop-Track Gym", type: "ghl", blurb: "Add a rooftop running track to a gym for cheap to boost retention and free social marketing.", supplier: "outdoor rubber running track flooring tiles" },
  { slug: "gripguard-floor-safety", title: "GripGuard Floor Safety", type: "ghl", blurb: "Apply anti-slip treatment to commercial tile floors and charge per square meter for a real liability-reducing service.", supplier: "anti slip floor treatment solution" },
  { slug: "collectible-pizza-box", title: "The Collectible Pizza Box", type: "ghl", blurb: "A printed, collectible pizza box that doubles as free social advertising and a collect-ten loyalty game.", supplier: "custom printed pizza boxes" },
  { slug: "croissantcup-drinkable-pastry-cafe", title: "CroissantCup Café — The Drinkable Pastry", type: "ghl", blurb: "A cafe concept built on a viral hollowed-croissant coffee cup that customers film and share for free marketing.", supplier: "kraft coffee cups custom printed" },
  { slug: "cookiedrop-vending", title: "CookieDrop Vending", type: "ghl", blurb: "Smart cookie vending machines in airports and captive hubs selling convenience 24/7 with no staff or rent.", supplier: "smart vending machine touchscreen cookie" },
  { slug: "twintalk-ai-avatars", title: "TwinTalk AI Avatars", type: "ghl", blurb: "Build and deploy real-time talking AI avatars as virtual assistants and support reps for businesses.", supplier: "real-time AI avatar platform" },
  { slug: "viral-signature-drink-cafe", title: "The Viral Signature Drink Cafe", type: "ghl", blurb: "A cafe built around one photogenic signature drink that customers film and share, driving free viral traffic.", supplier: "pistachio paste bulk" },
  { slug: "pourmoment-diy-espresso-cafe", title: "PourMoment — The DIY-Espresso Café", type: "ghl", blurb: "A café where customers pour their own espresso, creating a filmable moment that drives viral traffic.", supplier: "clear glass latte cup with mini espresso shot glass set" },
  { slug: "loaded-cafe", title: "Loaded Cafe", type: "ghl", blurb: "Turn ordinary coffee into a loaded, filmable dessert drink that customers share, driving traffic with zero ad spend.", supplier: "commercial espresso machine" },
  { slug: "rolling-led-ceiling-screens", title: "Rolling LED Ceiling Screens", type: "ghl", blurb: "Sell, rent, and install motorized rolling LED screens that turn any venue into a viral, futuristic ad space.", supplier: "rolling flexible LED display screen" },
  { slug: "lucky-cup-coffee-lottery-cafe", title: "Lucky Cup — The Coffee Lottery Café", type: "ghl", blurb: "A cafe growth system that turns coffee into a lottery with secret winner cups and filmed surprise giveaways.", supplier: "custom printed paper coffee cups scratch off" },
  { slug: "onecup-compostable", title: "OneCup Compostable", type: "shopify", blurb: "One-piece lid-free compostable takeaway cups sold wholesale to cafes that save money and go viral.", supplier: "compostable paper cup no lid foldable" },
  { slug: "container-pools-co", title: "Container Pools Co.", type: "shopify", blurb: "Convert used shipping containers into modern plunge pools that install in days, not months.", supplier: "swimming pool filtration pump system" },
  { slug: "layered-desserts-in-a-bottle", title: "Layered Desserts In A Bottle", type: "ghl", blurb: "Colorful layered desserts served in clear bottles, cheap to make and built for viral social sharing.", supplier: "clear plastic dessert bottle" },
  { slug: "slicecream-loaded-ice-cream-cakes", title: "SliceCream — Loaded Ice Cream Cakes", type: "ghl", blurb: "Sell loaded, post-worthy ice cream cake slices at premium margins for up to thirty thousand monthly.", supplier: "ice cream cake mold silicone springform set commercial" },
  { slug: "frosty-banana-co", title: "Frosty Banana Co.", type: "ghl", blurb: "Sell chocolate-dipped frozen bananas that cost 30 cents and sell for $3, at high volume from a cart or stall.", supplier: "chocolate melting tempering machine" },
  { slug: "emotion-cup-cafe", title: "The Emotion Cup Cafe", type: "ghl", blurb: "Coffee cups printed with spinnable emotions that turn disposable packaging into shareable, ad-free marketing.", supplier: "custom printed paper coffee cups" },
  { slug: "lumina-fake-sunlight-window-panels", title: "Lumina Windows — Realistic Fake-Sunlight Panels", type: "ghl", blurb: "Import and install ultra-realistic LED fake-window panels that bring simulated daylight to windowless commercial spaces.", supplier: "LED artificial sky window panel" },
  { slug: "frozenbrew-bars", title: "FrozenBrew Bars", type: "ghl", blurb: "Espresso, latte, and matcha frozen into popsicle bars sold at markets and wholesaled to stores.", supplier: "commercial popsicle mold machine" },
  { slug: "powered-walk-faster-shoes", title: "Powered Walk-Faster Shoes", type: "shopify", blurb: "Motorized strap-on shoes that boost your walking speed, a high-novelty gadget built to go viral.", supplier: "electric roller skates shoes" },
  { slug: "ledgemate-wall-mounted-fold-down-cafe-tables", title: "LedgeMate — Wall-Mounted Fold-Down Café Tables", type: "shopify", blurb: "Sell space-saving fold-down wall tables to cafés so they add seating without renting a bigger space.", supplier: "wall mounted folding drop leaf table bracket" },
  { slug: "trio-pizza", title: "Trio Pizza", type: "ghl", blurb: "Sell pizza in mix-and-match boxes of three individual pies to raise average order value without changing the recipe.", supplier: "individual pizza box trio custom printed" },
  { slug: "slap-chop-method", title: "The Slap Chop Method", type: "shopify", blurb: "Import a cheap slap-to-chop kitchen gadget and sell it at high margin through high-energy demo video marketing.", supplier: "hand press food chopper" },
  { slug: "creatorstack-all-in-one-tool-reselling", title: "CreatorStack — All-In-One Creator Tool Reselling", type: "ghl", blurb: "A near-zero-overhead service onboarding creators onto one all-in-one tool for setup fees, retainers, and affiliate income.", supplier: "Superprofile all-in-one creator platform subscription" },
  { slug: "easylight-charcoal", title: "EasyLight Charcoal", type: "shopify", blurb: "Self-lighting charcoal bundles with built-in wick and base that light in one match, no mess.", supplier: "hardwood charcoal briquette bulk" },
  { slug: "footpool-tables", title: "Footpool Tables", type: "ghl", blurb: "Giant soccer pool tables sold to bars and arcades that keep crowds playing and spending.", supplier: "foot pool soccer billiards table" },
  { slug: "mirror-tv-the-tv-that-disappears", title: "Mirror TV (The TV That Disappears)", type: "shopify", blurb: "A premium TV that looks like a wall mirror when off, sold to design-conscious homes and hotels.", supplier: "mirror tv two way smart display" },
  { slug: "peelpanel-peel-and-stick-solar-film", title: "PeelPanel — Peel-And-Stick Solar Film", type: "shopify", blurb: "Import and sell peel-and-stick flexible solar film for curved roofs, vehicles, and surfaces rigid panels can't reach.", supplier: "flexible thin film solar panel adhesive ETFE" },
  { slug: "remotedig", title: "RemoteDig", type: "ghl", blurb: "Operate excavators remotely over 5G and Starlink, selling teleoperation as a service to labor-short contractors.", supplier: "excavator teleoperation remote control console" },
  { slug: "nail-printing-studio", title: "The Nail Printing Studio", type: "ghl", blurb: "A digital nail printer that prints any design onto nails in minutes, powering a high-throughput nail-art studio.", supplier: "digital nail printer machine" },
  { slug: "photocake-edible-image-printing", title: "PhotoCake — Edible Image Printing", type: "ghl", blurb: "A custom-dessert business using an edible-ink printer to put any photo or logo onto cakes, cookies, and cupcakes.", supplier: "edible ink cake printer food printer" },
  { slug: "phoneshake-vending", title: "PhoneShake Vending", type: "ghl", blurb: "App-managed protein-shake vending machines in gyms earning thousands monthly and run remotely from your phone.", supplier: "smart protein shake vending machine app" },
  { slug: "strapbottle", title: "StrapBottle", type: "shopify", blurb: "A reusable water bottle with a built-in retractable strap for fully hands-free carrying.", supplier: "water bottle with shoulder strap" },
  { slug: "tear-off-sample-poster-marketing", title: "Tear-Off Sample Poster Marketing", type: "ghl", blurb: "Guerrilla launch campaigns with free samples attached to posters, turning tryers into filmable free advertisers.", supplier: "custom sachet packaging" },
  { slug: "slidecup-coffee-cups-with-hidden-card", title: "SlideCup — Coffee Cups With A Hidden Card", type: "shopify", blurb: "Sell cafés custom coffee cups with a hidden slide-out card that drives loyalty and free social posts.", supplier: "custom printed paper coffee cup with pull out card" },
  { slug: "bloombox-vending", title: "BloomBox Vending", type: "ghl", blurb: "Operate refrigerated flower vending machines selling fresh bouquets 24/7 in high-traffic, emotion-driven locations.", supplier: "refrigerated fresh flower vending machine" },
  { slug: "the-clip-factory", title: "The Clip Factory", type: "ghl", blurb: "An AI-powered content-repurposing service that turns one long video into a week of short reels for busy creators.", supplier: "content creator microphone kit" },
  { slug: "nevershatter-unbreakable-glassware", title: "NeverShatter — Unbreakable Glassware", type: "shopify", blurb: "Drinkware that looks and feels like real glass but won't shatter — sold DTC and wholesale to hospitality.", supplier: "unbreakable tritan shatterproof drinking glasses" },
];

export const SHOPIFY_URL = process.env.NEXT_PUBLIC_SHOPIFY_URL || "https://www.shopify.com/free-trial";
export const GHL_URL = process.env.NEXT_PUBLIC_GHL_URL || "https://www.gohighlevel.com";
export const SLACK_URL = process.env.NEXT_PUBLIC_SLACK_URL || "#";
// Free Whop community — the gate. Joining unlocks everything.
export const WHOP_FREE_URL =
  process.env.NEXT_PUBLIC_WHOP_URL ||
  "https://whop.com/benjis-business-blueprints/free-business-plans-suppliers";
export const PLANS_FOLDER_URL =
  process.env.NEXT_PUBLIC_PLANS_URL ||
  "https://drive.google.com/drive/folders/1I--Aa_uMJMtv5p95IHHBcEGPJj1gEA0u";

export const alibabaSearch = (q: string) =>
  `https://www.alibaba.com/trade/search?SearchText=${encodeURIComponent(q)}`;
